name: grafana-agent
version: '0.29.0'
summary: A telemetry collector for sending metrics, logs, and trace data
license: Apache-2.0
contact: simon.aronsson@canonical.com
issues: https://github.com/simskij/grafana-agent/issues
source-code: https://github.com/simskij/grafana-agent
website: https://grafana.com
description: |
  Grafana Agent is a telemetry collector for sending metrics, 
  logs, and trace data to the opinionated Grafana observability stack.
base: core22
grade: stable
confinement: strict
compression: lzo

plugs:
  config-file:
    interface: system-files
    read:
      - /etc/grafana-agent.yaml
  telemetry:
    interface: system-files
    read:
      - /proc/mdstat
      - /proc/schedstat
      - /proc/sys/kernel/random

apps:
  grafana-agent:
    daemon: simple 
    command: agent-wrapper
    install-mode: disable
    restart-condition: on-failure
    plugs:
      - network-bind
      - time-control
      - hardware-observe
      - mount-observe
      - network-observe
      - system-observe
      - config-file
      - telemetry
architectures:
  - build-on: amd64

parts:
  config:
    plugin: dump
    source: ./snap/local
    source-type: local
    override-build: |
      cp agent-wrapper $CRAFT_PART_INSTALL/
  grafana-agent:
    plugin: go
    source: https://github.com/grafana/agent
    source-type: git
    source-tag: "v$SNAPCRAFT_PROJECT_VERSION"
    build-packages:
      - build-essential
      - golang
      - libsystemd-dev
      - libbpfcc-dev
      - bpfcc-tools
    stage-packages:
      - libsystemd0
      - libbpfcc
      - bpfcc-tools
    build-environment:
      - USE_CONTAINER: 0
      - GOFLAGS: "-mod=readonly"
    override-build: |
      make agent agentctl
      cp build/agent $CRAFT_PART_INSTALL/
      cp build/agentctl $CRAFT_PART_INSTALL/
