name: grafana-agent
version: '0.25.1'
summary: A telemetry collector for sending metrics, logs, and trace data
license: Apache-2.0
contact: simon.aronsson@canonical.com
issues: https://github.com/simskij/grafana-agent/issues
source-code: https://github.com/simskij/grafana-agent
website: https://grafana.com
description: |
  Grafana Agent is a telemetry collector for sending metrics, 
  logs, and trace data to the opinionated Grafana observability stack.
base: core22
grade: stable
confinement: classic
compression: lzo

apps:
  grafana-agent:
    command: grafana-agent

architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64
  - build-on: s390x
  - build-on: ppc64el

parts:
  grafana-agent:
    plugin: go
    source: https://github.com/grafana/agent
    source-type: git
    source-tag: "v$SNAPCRAFT_PROJECT_VERSION"
    build-snaps: [go]
    build-environment:
      - CGO_ENABLED: "0"
      - GOFLAGS: "-mod=readonly"
    override-build: |
      go mod download
      go build -ldflags "-s -w" -o agent ./cmd/agent
      cp agent $SNAPCRAFT_PART_INSTALL/grafana-agent
    stage:
      - grafana-agent
